spring:
  servlet:
     multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://ingot-db-mysql:3306/hwtv_db?useUnicode=true&characterEncoding=UTF8&useSSL=false

mybatis:
  type-aliases-package: com.ingot.ha.model.domain
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  not-empty: true
  mappers: com.ingot.common.mybatis.MyMapper
  identity: MYSQL

security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: ingotHwtvAdminSecret
      access-token-uri: http://ingot-auth-center:8050/oauth/token
      user-authorization-uri: http://ingot-auth-center:8050/oauth/authorize
    resource:
      id: hwtv-admin-resource
      user-info-uri: http://ingot-auth-center:8050/user
      prefer-token-info: false
      jwt:
        key-uri: http://ingot-auth-center:8050/oauth/token_key
ingot:
  job:
    xxl:
      admin:
        addresses: http://${INGOT_TMC_HOST:ingot-task-manager-center}:8060
      executor:
        appname: ${spring.application.name}
        ip:
        port: 9900
        logpath: /data/ingot/logs/${spring.application.name}/jobhandler
        logretentiondays: -1
      accessToken: '{cipher}AQAAyCI7/2E40wP2e5RMuZ6pgAETmxvQjaGuLHMIFHynP2tDC8LCo4t7mlRVgU0h+s8Jbxbb+e7pEG9th/HeyPfNQ+GfZQSTn5cfLtHbJMMZYLN7yKOYJl7I+9rku3OiYyJideYU4BYG+EMU+5Xzq+3zfsY7HvsPAn561wo9kfwjPWnRlPprwDJJgptfMygbjmbFoUo/jeJ/GXojALNME76oSp6gxl3bqrRaTfCGYL5iPZNJbXTMFgC1IyNpvaa+DUa6WQ1KD3Dk4wM3pmfe+OUQuaEL7W8hoyinlWidOjrFOvu+bQO7241jMFByKDFwxx3i/EAHQInu4brvaryS52dLijAoZC59oZuCghcxWzmVrbrXiAAgSOd6ZSTuQtmevRjD8qeXhmIsVuPXNEcmMAOm'
  application:
    dataCenterId: 5
    machineId: 0
  oauth2:
    resource:
      permit:
       - /login
       - /token
