spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://ingot-db-mysql:3306/hw_ingot_ac_db?useUnicode=true&characterEncoding=UTF8&useSSL=false

mybatis:
  type-aliases-package: com.ingot.auth.model.domain
  mapper-locations: classpath*:mapper/*.xml,classpath*:sdk/mapper/*.xml

security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: GwCwru42UrxQTUFLWOAsJqa3/+WSTlRMwiQDBq8KOgI=
      access-token-uri: http://ingot-auth-center:8050/oauth/token
      user-authorization-uri: http://ingot-auth-center:8050/oauth/authorize
    resource:
      id: ingot-resource-ac

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:ocnt-123@ingot-eureka-node1:8001/eureka/,http://root:ocnt-123@ingot-eureka-node2:8001/eureka/

ingot:
  application:
    dataCenterId: 0
    machineId: 0
  oauth2:
    tokenStore: jwt
    rsaSecret: 1asd21!@#asd12
    resource:
      permit:
      - /auth/user/refreshToken
      - /auth/code/**
      - /login
      - /test/a
  job:
    xxl:
      admin:
        addresses: http://ingot-task-manager-center-node1:8060,http://ingot-task-manager-center-node2:8060
