spring:
  servlet:
     multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://ingot-db-mysql:3306/hwtv_db?useUnicode=true&characterEncoding=UTF8&useSSL=false

mybatis:
  type-aliases-package: com.ingot.hwapp.model.domain
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  not-empty: true
  mappers: com.ingot.common.mybatis.MyMapper
  identity: MYSQL

security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: 3RWX9+UQF2XZQBafc8zPsqbPwI2eJN4dM6Feh8ykg8U=
      access-token-uri: http://ingot-auth-center:8050/oauth/token
      user-authorization-uri: http://ingot-auth-center:8050/oauth/authorize
    resource:
      id: hwtv-app-resource
      user-info-uri: http://ingot-auth-center:8050/user
      prefer-token-info: false
      jwt:
        key-uri: http://ingot-auth-center:8050/oauth/token_key
ingot:
  application:
    dataCenterId: 6
    machineId: 0
  oauth2:
    resource:
      permit:
        - /update/**
        - /detail/**
        - /live/**
        - /movie/**
        - /main/**
        - /sms/**
        - /resource/**
        - /user/thirdparty/login
        - /user/area
        - /pay/ali/notify
        - /pay/wx/notify
        - /pay/qr/**
      userPermit:
        - /update/**
        - /detail/**
        - /live/**
        - /movie/**
        - /main/**
        - /sms/**
        - /resource/**
        - /user/thirdparty/login
        - /user/area
        - /pay/ali/notify
        - /pay/wx/notify
        - /pay/qr/**