spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://ingot-db-mysql:3306/hwtv_db?useUnicode=true&characterEncoding=UTF8&useSSL=false
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: S/Jn+G0ckFzoUqyjnKDhWeTjnF9NWNzrrYuZ29Eb4NU=
      access-token-uri: http://ingot-auth-center:8050/oauth/token
      user-authorization-uri: http://ingot-auth-center:8050/oauth/authorize
    resource:
      id: ingot-hwtv-resource-resource
      user-info-uri: http://ingot-auth-center:8050/user
      prefer-token-info: false
      jwt:
        key-uri: http://ingot-auth-center:8050/oauth/token_key
ingot:
  application:
    dataCenterId: 7
    machineId: 0