spring:
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:ingot-db-mysql}:${MYSQL_PORT:3306}/hw_ingot_tmc_db?useUnicode=true&characterEncoding=UTF8&useSSL=false

mybatis:
  type-aliases-package: com.ingot.uc.model.domain
  mapper-locations: classpath*:mapper/*.xml,classpath*:sdk/mapper/*.xml,classpath:/mybatis-mapper/*Mapper.xml

security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: '{cipher}AQBxB1eI6JrOmnv/bzpeZEej+dQxEz/+BST3MJ47yafiFKKfiVF4tqwUyv/syPdQGOIniB8qAqavHXsWJDO8OrckpeVb9iAzoCV+h+KaCFme78ELfkQNN7k+d6J2RrA1/h9eLARolAR/ytehx5m7lGNNQnPTlr/LKHOCugV6Q0HqehLAu3T3pNXgtpOM3sa+lpMcM/Bx1B79KJKYqhE6UbI0I2RmyhfCoAaCUc8y/54sFsLGIxabtufMwM0zutgkYAI+CdveJUdJAA3JxCu8JV/DArYUcVY8IwEMa+5aqWL+Jw6TBdldyW5UDnI2rF2MX8oHj5EVe1NBjurZ3YZ77k6C55rqklNnl4LKRpJEvWOhd9FzkCoS/Yax8fKpgBMxrRmEmMvKsgvwDpbcb+F6HnTueLVoDZ1QpaLSh3L9yu/qOQ=='
      access-token-uri: http://ingot-auth-center:8050/oauth/token
      user-authorization-uri: http://ingot-auth-center:8050/oauth/authorize
    resource:
      id: ingot-resource-tmc
      user-info-uri: http://ingot-auth-center:8050/user
      prefer-token-info: false
      jwt:
        key-uri: http://ingot-auth-center:8050/oauth/token_key

ingot:
  application:
    dataCenterId: 3
    machineId: 0
  oauth2:
    resource:
      permit:
        - /**
      userPermit:
        - /**
